version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: nanika_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - nanika_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nanika_api
    user: "root"
    restart: unless-stopped
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      
      PASS_PEPPER: ${PASS_PEPPER}
      NANIKA_JWT_SECRET: ${NANIKA_JWT_SECRET}
      RESEND_API_KEY: ${RESEND_API_KEY}
      EMAIL_VALIDATION_API_KEY: ${EMAIL_VALIDATION_API_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      IMGUR_CLIENT_ID: ${IMGUR_CLIENT_ID}
      NANIKA_STORAGE_PATH: /app/nanika_storage/
    volumes:
      - ./nanika_storage:/app/nanika_storage
    networks:
      - nanika_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nanika_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    networks:
      - nanika_network

networks:
  nanika_network:
    driver: bridge

volumes:
  pg_data:
